namespace ArchipelagoP5RMod.Types;

public enum Confidant: ushort
{
    Igor = 1,
    Morgana = 2,
    Makoto = 3,
    Haru = 4,
    Yusuke = 5,
    Sojiro = 6,
    Ann = 7,
    Ryuji = 8,
    Akechi = 9,
    Futaba = 10,
    Chihaya = 11,
    JustineCaroline = 12,
    Iwai = 13,
    Takemi = 14,
    Kawakami = 15,
    Ohya = 16,
    Shinya = 17,
    Hifumir = 18,
    Mishima = 19,
    Yoshida = 20,
    Sae = 21,
    World = 22,
    MakotoFriend = 23,
    HaruFriend = 24,
    AnnFriend = 25,
    FutabaFriend = 26,
    ChihayaFriend = 27,
    TakemiFriend = 28,
    KawakamiFriend = 29,
    OhyaFriend = 30,
    HifumiFriend = 31,
    SaeFriend = 32, // Unused
    Kasumi = 33,
    KasumiFriend = 34,
    Maruki = 35,
    Sumire = 36,
    SumireFriend = 37,
}